name: 'Main_Result_BA_Graph'
num_seeds: 30

data_params:
  n: 1000
  d: 10
  graph_type: 'ba'
  cate_type: 'simple_h'
  real_data_name: null
  noise_level: 0.5
model_params:
  num_layers: 2
  hidden_dim: 32

training_params:
  nuisance_epochs: 150
  cate_epochs: 200
  lr: 0.001
