name: 'SemiSynthetic_Cora'
num_seeds: 30

data_params:
  n: null # Not needed, determined by data
  d: null # Not needed, determined by data
  graph_type: null # Not needed, determined by data
  cate_type: 'simple_h'
  real_data: 'cora' # Key change

model_params:
  num_layers: 2
  hidden_dim: 32

training_params:
  nuisance_epochs: 150
  cate_epochs: 200
  lr: 0.001
